"""End-to-end pipeline test on SYNTHETIC data.

Generates a clearly-labeled synthetic TED raw tree under tests/tmp/output/,
runs 03_classify -> 04_build_panel -> 05..09 with TESI_OUTPUT_DIR pointing
there (the real output/ tree is never touched), and asserts:

- parsing/cleaning rules D1, D3, C4 fire exactly on the planted records
- Z1: failed chunks -> NaN, complete chunks -> real zeros
- FX conversion matches the synthetic rates
- the CS estimator recovers the PLANTED positive effect on cyber tenders
- the placebo (generic ICT, generated with NO effect) stays near zero
- all expected figures/tables/results files exist

This validates the CODE. It says nothing about real TED data.
"""
from __future__ import annotations

import gzip
import json
import os
import subprocess
import sys
from pathlib import Path

import numpy as np
import pandas as pd

TESTS = Path(__file__).resolve().parent
ROOT = TESTS.parent
TMP_OUT = TESTS / "tmp" / "output"
RAW = TMP_OUT / "ted_raw"
REF = TMP_OUT / "reference"

SEED = 7
MONTHS = pd.period_range("2021-01", "2026-07", freq="M").astype(str).tolist()
FAILED_CHUNKS = [("FR", "2026-05"), ("FR", "2026-06")]
ACTIVITIES = ["health", "gen-pub", "education", "transport", "gas", "defence"]
PROCEDURES = ["open", "restricted", "neg-wo-call", "comp-neg"]

with open(ROOT / "config" / "countries.json", encoding="utf-8") as f:
    CCFG = json.load(f)
SAMPLE = {k: v for k, v in CCFG["countries"].items() if v["in_default_sample"]}

CYBER_TITLES = {
    "IT": "Servizi di sicurezza informatica e SOC h24",
    "FR": "Services de cybersécurité et test d'intrusion",
    "DE": "IT-Sicherheit und Penetrationstest",
    "ES": "Servicios de ciberseguridad y cifrado",
    "HR": "Usluge kibernetičke sigurnosti",
    "LV": "Kiberdrošības operāciju centrs",
    "LT": "Kibernetinio saugumo paslaugos",
    "BE": "Cyberbeveiliging en penetratietest",
    "HU": "Kiberbiztonsági szolgáltatások és sérülékenységvizsgálat",
    "SK": "Kybernetická bezpečnosť a šifrovanie",
    "FI": "Kyberturvallisuuden palvelut",
    "DK": "Cybersikkerhed og penetrationstest",
    "SE": "Cybersäkerhet och penetrationstest",
    "IE": "Cybersecurity services ISO 27001",
}
GENERIC_TITLES = ["Software development services", "IT consultancy",
                  "Application maintenance", "Data centre services",
                  "ERP implementation"]


def currency_for(c2: str, month: str) -> str:
    if c2 == "HR":
        return "HRK" if month < "2023-01" else "EUR"
    return {"HU": "HUF", "DK": "DKK", "SE": "SEK"}.get(c2, "EUR")


FX = {"HUF": 385.0, "DKK": 7.46, "SEK": 11.2, "CZK": 24.5, "HRK": 7.5345}


def make_notice(rng, pn, c2, month, cpv_list, title, form_type,
                buyer_max=8, accel_p=0.05):
    day = int(rng.integers(1, 28))
    date = f"{month}-{day:02d}"
    cur = currency_for(c2, month)
    has_value = rng.random() > 0.4
    amount = float(np.round(np.exp(rng.normal(12, 1)), 2)) if has_value else None
    n = {
        "publication-number": pn,
        "publication-date": f"{date}+01:00",
        "buyer-country": SAMPLE[c2]["iso3"],
        "buyer-name": {"mul": [f"SYNTHETIC FIXTURE buyer {c2} "
                               f"{int(rng.integers(0, buyer_max))} — NOT REAL DATA"]},
        "notice-title": {"eng": [title]} if rng.random() < 0.5
        else {"und": title},
        "form-type": form_type,
        "classification-cpv": cpv_list if len(cpv_list) > 1 else cpv_list[0],
        "main-activity": str(rng.choice(ACTIVITIES)),
        "procedure-type": str(rng.choice(PROCEDURES, p=[0.6, 0.2, 0.1, 0.1])),
        "procedure-accelerated": "true" if rng.random() < accel_p else "false",
        "_country_iso2": c2,
    }
    if form_type == "result":
        if amount is not None:
            n["total-value"] = amount
            n["total-value-cur"] = cur
    else:
        if amount is not None:
            n["estimated-value"] = {"value": amount}
            n["estimated-value-cur"] = cur
    return n


def gen_fixture():
    rng = np.random.default_rng(SEED)
    RAW.mkdir(parents=True, exist_ok=True)
    REF.mkdir(parents=True, exist_ok=True)
    (TESTS / "tmp" / "SYNTHETIC_DATA_README.txt").write_text(
        "Everything under tests/tmp is SYNTHETIC, generated by run_e2e.py "
        "for pipeline validation. It is NOT TED data and must never be "
        "analyzed as such.\n")

    manifest = {"chunks": {}, "meta": {"template": "SYNTHETIC", "fields": [],
                                       "server_cpv_filter": True,
                                       "window": [MONTHS[0], MONTHS[-1]]}}
    pn_counter = 1
    hu_huf_total = 0.0

    for c2, meta in SAMPLE.items():
        big = c2 in ("IT", "DE", "ES", "FR")
        treat = meta["treatment_date"]
        treat_month = None if treat == "never" else treat[:7]
        cdir = RAW / c2
        cdir.mkdir(exist_ok=True)
        for month in MONTHS:
            if (c2, month) in FAILED_CHUNKS:
                manifest["chunks"][f"{c2}/{month}"] = {
                    "status": "failed", "error": "SYNTHETIC planted failure",
                    "month": month}
                continue
            post = treat_month is not None and month >= treat_month
            lam_strict = 2.0 * (2.2 if post else 1.0)
            lam_broadkw = 1.5 * (2.2 if post else 1.0)
            lam_ict = 40.0 if big else 14.0   # NO treatment effect (placebo)
            notices = []

            def emit(cpvs, title, k, cyber=False):
                nonlocal pn_counter, hu_huf_total
                for _ in range(k):
                    form = rng.choice(["competition", "result", "planning",
                                       "cont-modif"], p=[0.55, 0.35, 0.05, 0.05])
                    # unique suffix: real TED titles rarely collide; keeps the
                    # D3 rule from firing outside the planted pair.
                    # planted post-treatment dynamics for cyber notices:
                    # wider buyer pool (extensive margin) + more accelerated
                    # procedures (H3)
                    n = make_notice(rng, f"{pn_counter:06d}-{month[:4]}", c2,
                                    month, cpvs,
                                    f"{title} — procedura {pn_counter}",
                                    str(form),
                                    buyer_max=14 if (cyber and post) else 8,
                                    accel_p=0.20 if (cyber and post) else 0.05)
                    pn_counter += 1
                    notices.append(n)

            emit(["72800000-9", "72000000"], CYBER_TITLES[c2],
                 int(rng.poisson(lam_strict)), cyber=True)
            emit(["72500000"], CYBER_TITLES[c2], int(rng.poisson(lam_broadkw)),
                 cyber=True)
            emit(["72500000"], str(rng.choice(GENERIC_TITLES)),
                 int(rng.poisson(lam_ict * 0.3)))
            emit(["72200000"], str(rng.choice(GENERIC_TITLES)),
                 int(rng.poisson(lam_ict * 0.7)))

            # planted cleaning-rule probes, one country-month only
            if c2 == "IT" and month == "2024-03":
                dup = make_notice(rng, "DUP001-2024", c2, month,
                                  ["72800000"], CYBER_TITLES[c2], "competition")
                notices += [dup, dict(dup)]                      # D1
                rep1 = make_notice(rng, "REP001-2024", c2, month,
                                   ["72500000"], "Identical republished lot — "
                                   "sicurezza informatica", "competition")
                rep2 = dict(rep1)
                rep2["publication-number"] = "REP002-2024"
                rep1["buyer-name"] = rep2["buyer-name"] = {"ita": ["SYNTHETIC "
                                                                  "buyer X"]}
                notices += [rep1, rep2]                          # D3
                trap = make_notice(rng, "TRAP01-2024", c2, month,
                                   ["79417000"], "Servizi di sicurezza "
                                   "informatica (safety!)", "competition")
                notices.append(trap)                             # C4

            with gzip.open(cdir / f"{month}.jsonl.gz", "wt",
                           encoding="utf-8") as f:
                for n in notices:
                    f.write(json.dumps(n, ensure_ascii=False) + "\n")
                    if (c2 == "HU" and n.get("form-type") == "competition"):
                        v = n.get("estimated-value")
                        if isinstance(v, dict):
                            hu_huf_total += v["value"]
            manifest["chunks"][f"{c2}/{month}"] = {
                "status": "complete", "month": month,
                "fetched": len(notices), "total_reported": len(notices),
                "pagination_dupes_dropped": 0,
                "file": f"{c2}/{month}.jsonl.gz"}

    with open(RAW / "manifest.json", "w", encoding="utf-8") as f:
        json.dump(manifest, f, indent=1)

    hicp_rows, fx_rows = [], []
    for i, month in enumerate(pd.period_range("2020-01", "2026-08",
                                              freq="M").astype(str)):
        for c2 in SAMPLE:
            hicp_rows.append({"geo": c2, "month": month,
                              "hicp_i15": 105 * (1.003 ** i),
                              "hicp_2021_100": 100 * (1.003 ** (i - 15))})
        for cur, rate in FX.items():
            fx_rows.append({"currency": cur, "month": month,
                            "nac_per_eur": rate})
    pd.DataFrame(hicp_rows).to_csv(REF / "hicp_monthly.csv", index=False)
    pd.DataFrame(fx_rows).to_csv(REF / "fx_monthly.csv", index=False)
    return hu_huf_total


def run_step(script, *args):
    env = dict(os.environ, TESI_OUTPUT_DIR=str(TMP_OUT), TESI_NBOOT="99",
               MPLBACKEND="Agg")
    r = subprocess.run([sys.executable, str(ROOT / "src" / script), *args],
                       capture_output=True, text=True, env=env)
    tail = (r.stdout + r.stderr)[-1500:]
    print(f"--- {script} (exit {r.returncode})\n{tail}")
    return r.returncode, r.stdout + r.stderr


def main():
    import shutil
    if (TESTS / "tmp").exists():
        shutil.rmtree(TESTS / "tmp")
    hu_huf_total = gen_fixture()
    failures = []

    def check(name, cond, detail=""):
        status = "PASS" if cond else "FAIL"
        print(f"[{status}] {name}" + (f" — {detail}" if detail and not cond else ""))
        if not cond:
            failures.append(name)

    # --- unit checks for review-driven rules (parser, keywords) ---
    import importlib.util
    spec = importlib.util.spec_from_file_location(
        "clf", ROOT / "src" / "03_classify.py")
    clf = importlib.util.module_from_spec(spec)
    sys.path.insert(0, str(ROOT / "src"))
    spec.loader.exec_module(clf)
    from ted_common import fold_text
    check("V1: '500.000' parses as 500000 (dot-grouped)",
          clf._parse_number_string("500.000") == 500000.0)
    check("V1: '1.234.567,89' parses as 1234567.89",
          clf._parse_number_string("1.234.567,89") == 1234567.89)
    check("V1: '1234.56' parses as 1234.56",
          clf._parse_number_string("1234.56") == 1234.56)
    check("V1: lot list sums to procedure total",
          clf.scalar_value([100000, 200000, 300000]) == 600000.0)
    check("V3: multicurrency -> NaN",
          clf.resolve_value([100, 200], ["EUR", "SEK"]) == (None, None, True))
    check("KW: ALL-CAPS 'SOC. COOP.' is not a SOC",
          clf.keyword_hits(fold_text(
              "AFFIDAMENTO SERVIZI INFORMATICI ALLA SOC. COOP. ALFA")) == [])
    check("KW: mixed-case SOC still matches",
          "SOC" in clf.keyword_hits(fold_text("Servizi SOC h24 per l'ente")))
    check("KW: Spanish 'vulnerabilidades' matches",
          "vulnerabili" in clf.keyword_hits(fold_text(
              "Gestion de vulnerabilidades de los sistemas")))
    check("KW: 'securite du site' does NOT match",
          clf.keyword_hits(fold_text(
              "Maintenance et sécurité du site internet de la ville")) == [])
    check("KW: 'audit security' does not hit 'it security'",
          clf.keyword_hits(fold_text(
              "Audit security and compliance software")) == [])

    rc, _ = run_step("03_classify.py")
    check("03 classify exits 0", rc == 0)
    cls = pd.read_parquet(TMP_OUT / "notices_classified.parquet")

    check("D1: exact duplicate dropped",
          (cls["publication_number"] == "DUP001-2024").sum() == 1)
    reps = cls[cls["publication_number"].isin(["REP001-2024", "REP002-2024"])]
    check("D3: republication dropped", len(reps) == 1, f"found {len(reps)}")
    trap = cls[cls["publication_number"] == "TRAP01-2024"]
    check("C4: 79417000 + keyword is NOT cyber",
          len(trap) == 1 and trap.iloc[0]["category"] == "other",
          str(trap["category"].tolist()))
    check("dash CPV parsed (72800000-9 -> strict)",
          (cls[cls["publication_number"] == "DUP001-2024"]["category"]
           == "cyber_strict").all())
    for cat in ["cyber_strict", "cyber_broad", "ict_generic"]:
        check(f"category {cat} present", (cls["category"] == cat).any())
    kwless = cls[(cls["category"] == "ict_generic")
                 & cls["cpv_all"].str.startswith("725")]
    check("725* without keywords stays ict_generic", len(kwless) > 0)
    post_ef = cls[cls["month"] >= "2023-11"]["is_post_eforms"]
    check("is_post_eforms true after cutover",
          bool(post_ef.astype(bool).all()) if len(post_ef) else False)

    rc, _ = run_step("04_build_panel.py")
    check("04 panel exits 0", rc == 0)
    panel = pd.read_csv(TMP_OUT / "panel_monthly.csv")
    check("panel full grid",
          len(panel) == len(SAMPLE) * len(MONTHS) * 4,
          f"{len(panel)} rows")
    fr_fail = panel[(panel["country"] == "FR") & (panel["month"] == "2026-05")]
    check("Z1: failed chunk -> NaN", fr_fail["n_tenders"].isna().all())
    ok_rows = panel[~panel.apply(
        lambda r: (r["country"], r["month"]) in FAILED_CHUNKS, axis=1)]
    check("Z1: complete chunks never NaN counts",
          ok_rows["n_tenders"].notna().all())
    check("zeros exist in complete chunks (0 vs NaN distinction)",
          (ok_rows["n_tenders"] == 0).any())

    hu = panel[(panel["country"] == "HU")]
    hu_eur = hu["est_total_eur"].sum()
    expected = hu_huf_total / FX["HUF"]
    check("F1: HUF converted at synthetic rate",
          abs(hu_eur - expected) / max(expected, 1) < 0.01,
          f"panel {hu_eur:.0f} vs expected {expected:.0f}")
    check("P1: real values populated", hu["est_total_eur_real"].sum() > 0)
    check("post_eforms dummy", set(panel[panel["month"] >= "2023-11"]
                                   ["post_eforms"]) == {1})
    it_treat = panel[(panel["country"] == "IT") & (panel["month"] == "2024-10")]
    check("treatment timing IT 2024-10 treated=1",
          (it_treat["treated"] == 1).all() and (it_treat["rel_month"] == 0).all())

    rc, _ = run_step("05_descriptives.py")
    check("05 descriptives exits 0", rc == 0)
    rc, _ = run_step("06_event_study.py")
    check("06 event study exits 0", rc == 0)
    rc, out07 = run_step("07_csdid.py")
    check("07 CS-DiD exits 0", rc == 0)
    rc, _ = run_step("08_placebo.py")
    check("08 placebo exits 0", rc == 0)
    rc, _ = run_step("09_write_results.py")
    check("09 results exits 0", rc == 0)

    figs = sorted(p.name for p in (TMP_OUT / "figs").glob("*.png"))
    for f in ["fig01_n_cyber_by_country.png", "fig02_cyber_share_by_country.png",
              "fig03_group_means.png", "fig04_value_cyber_by_country.png",
              "fig05_event_study_n_cyber.png", "fig06_event_study_share.png",
              "fig07_csdid_event_n_cyber.png", "fig08_placebo_event_study.png",
              "fig09_placebo_csdid.png"]:
        check(f"figure {f}", f in figs)

    # judge effects against their own standard errors (overall aggregation)
    with open(TMP_OUT / "tables" / "csdid_overall.json") as f:
        ov = json.load(f)["y_cyber"]
    with open(TMP_OUT / "tables" / "placebo_overall.json") as f:
        ov_pl = json.load(f)
    att, se = ov["att_overall"], ov.get("att_overall_se")
    check("CS recovers planted cyber effect (ATT>0, significant when SE known)",
          att > 0.15 and (se is None or att > 1.64 * se),
          f"ATT {att:.3f}, SE {se}")
    att_pl, se_pl = ov_pl["att_overall"], ov_pl.get("att_overall_se")
    check("placebo consistent with zero",
          abs(att_pl) < 0.1 or (se_pl is not None and abs(att_pl) < 1.96 * se_pl),
          f"placebo ATT {att_pl:.3f}, SE {se_pl}")
    check("RESULTS_PRELIMINARY.md written",
          (TMP_OUT / "RESULTS_PRELIMINARY.md").exists())

    # ---------------- §3.7 v2 chain ----------------
    tmp_base = TMP_OUT.parent
    rc, _ = run_step("10_build_panels_v2.py")
    check("10 panels v2 exits 0", rc == 0)
    p2_path = tmp_base / "data" / "panel_country_month.csv"
    check("panel_country_month.csv written", p2_path.exists())
    if p2_path.exists():
        p2 = pd.read_csv(p2_path)
        need_cols = ["n_cyber_tenders", "n_new_buyers_cyber", "n_buyers_cyber",
                     "share_cyber_n", "accel_share_ict", "negwc_share_ict",
                     "n_modifications_ict", "est_value_cyber_real_win",
                     "est_value_incumbent_real", "n_placebo45_tenders",
                     "treat_month", "treat_month_alt", "treat_month_it_alt",
                     "post_eforms"]
        check("panel v2 has all §3.7 columns",
              all(c in p2.columns for c in need_cols),
              str([c for c in need_cols if c not in p2.columns]))
        check("panel v2 window frozen at 2026-07",
              p2["month"].max() == "2026-07", p2["month"].max())
        check("panel v2 Z1: FR 2026-05 NaN",
              p2.loc[(p2["country"] == "FR") & (p2["month"] == "2026-05"),
                     "n_cyber_tenders"].isna().all())
        check("panel v2 div45 NaN (not extracted)",
              p2["n_placebo45_tenders"].isna().all())
        check("panel v2 IT alt cohort = 2026-01",
              (p2.loc[p2["country"] == "IT", "treat_month_it_alt"] ==
               "2026-01").all())
    check("sector panel written",
          (tmp_base / "data" / "panel_country_sector_month.csv").exists())
    check("VARIABLES.md written", (tmp_base / "data" / "VARIABLES.md").exists())

    rc, _ = run_step("11_estimation.py")
    check("11 estimation exits 0", rc == 0)
    ev = tmp_base / "results" / "tables" / "h1_n_cyber_event.csv"
    check("h1 event table written", ev.exists())
    if ev.exists():
        h1 = pd.read_csv(ev)
        att_post = h1[h1["rel_month"].between(0, 18)]["att"].mean()
        att_pre = h1[h1["rel_month"] < 0]["att"].mean()
        check("h1 recovers planted effect (post-pre > 0.15)",
              att_post - att_pre > 0.15,
              f"post {att_post:.3f} pre {att_pre:.3f}")
    ext = tmp_base / "results" / "tables" / "h1_extensive_new_buyers_event.csv"
    check("h1 extensive-margin table written", ext.exists())
    check("h3 accel (ICT-wide) table written",
          (tmp_base / "results" / "tables" / "h3_accel_share_event.csv").exists())
    check("h3 accel (cyber) table written",
          (tmp_base / "results" / "tables" /
           "h3_accel_share_cyber_event.csv").exists())
    # planted accel effect (cyber prob 0.05 -> 0.20 post) asserted on raw
    # panel means: the CS event-time estimates on shares of 2-5 monthly
    # tenders are too noisy for a stable threshold (documented in LIMITS);
    # this validates the variable construction, which is what the test owns
    tr2 = p2[p2["treat_month"].notna()]
    did = ((tr2[tr2["month"] >= tr2["treat_month"]]["accel_share_cyber"].mean()
            - tr2[tr2["month"] < tr2["treat_month"]]["accel_share_cyber"].mean())
           - 0.0)
    check("h3 planted accel effect visible in raw panel DiD (> 0.08)",
          did > 0.08, f"raw DiD {did:.3f}")
    check("h4 riskzone table written",
          (tmp_base / "results" / "tables" / "h4_riskzone_event.csv").exists())
    check("anticipation-3 table written",
          (tmp_base / "results" / "tables" /
           "rob_anticipation3_n_cyber_event.csv").exists())
    check("TWFE/SA robustness table written",
          (tmp_base / "results" / "tables" / "rob_twfe_sa_n_cyber.csv").exists())
    check("HonestDiD beta export written",
          (tmp_base / "results" / "tables" /
           "sensitivity_honestdid_beta.csv").exists())

    rc, _ = run_step("12_placebos.py")
    check("12 placebos exits 0", rc == 0)
    pb = tmp_base / "results" / "tables" / "placebo_b_ict_generic_event.csv"
    check("placebo (b) table written", pb.exists())
    if pb.exists():
        pbd = pd.read_csv(pb)
        pb_post = pbd[pbd["rel_month"] >= 0]["att"].mean()
        pb_pre = pbd[pbd["rel_month"] < 0]["att"].mean()
        check("placebo (b) near zero (|post-pre| < 0.12)",
              abs(pb_post - pb_pre) < 0.12,
              f"post {pb_post:.3f} pre {pb_pre:.3f}")
    check("pretrend tests written",
          (tmp_base / "results" / "tables" / "pretrend_tests.csv").exists())

    rc, _ = run_step("13_validation_sample.py")
    check("13 validation draw exits 0", rc == 0)
    check("validation sample written",
          (tmp_base / "results" / "validation_sample.csv").exists())

    rc, _ = run_step("14_write_results_v2.py")
    check("14 results v2 exits 0", rc == 0)
    check("RESULTS.md written", (tmp_base / "results" / "RESULTS.md").exists())
    check("LIMITS.md written", (tmp_base / "results" / "LIMITS.md").exists())
    figs2 = {p.name for p in (tmp_base / "figures").glob("*.png")} \
        if (tmp_base / "figures").exists() else set()
    for f in ["h1_n_cyber.png", "h1_value.png", "h2_share_n.png",
              "h3_accel_share.png", "h4_riskzone.png",
              "placebo_b_ict_generic.png"]:
        check(f"figure {f}", f in figs2)

    print(f"\n{'=' * 60}\n{len(failures)} failures" +
          (f": {failures}" if failures else " — ALL CHECKS PASSED"))
    sys.exit(1 if failures else 0)


if __name__ == "__main__":
    main()
